---
title: "Connect to GitHub"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

https://happygitwithr.com/push-pull-github

## Make a repo on GitHub
Repos you create on GitHub have a clone URL, which you can find by clicking on the green code button. You have the option to select an HTTPS or an SSH type URL. Select the one you prefer. Whichever you select, the URL will contain a username and the repo name.

## Clone a repo to your local computer
Cloning a repo from GitHub to your local computer can be done using command line Git. Firstly, select the directory you want the clone to live in. Then, clone the repo with:
`git clone <URL>`

Once you have cloned the repo, you make it your working directory and you're ready to go.

You can list the items in the cloned repo with `ls` and get information on its connection to GitHub with `git remote show origin`. 

## Make a local change, commit and push
When you make a change to the files in the repo, you need to commit those changes then push them to your remote repo on GitHub.

We first stage the files to commit using: 
`git add <file name>`

We then commit using:
`git commit -m "message"`

And finish by pushing to GitHub:
`git push`

